### ISSUE TITLE
Instructions to run hasjob locally seems not explained very well or outdated

### ISSUE THREAD

**Issue by jitendravyas** [hasgeek/hasjob#193]
I have installed Python, pip and flask but still not able to run the project on OSX.

I didn't get this part 

```
To run the server in development mode:

$ python runserver.py
```

getting this error

````
~/o/hasjob git:master ❯❯❯ python runserver.py                                         ✱
Traceback (most recent call last):
  File "runserver.py", line 3, in <module>
    from hasjob import app, init_for, models
  File "/Users/jitendravyas/ola-projects/hasjob/hasjob/__init__.py", line 12, in <module>
    from baseframe import baseframe, assets, Version
  File "/Library/Python/2.7/site-packages/baseframe/__init__.py", line 216, in <module>
    from .views import *    # NOQA
  File "/Library/Python/2.7/site-packages/baseframe/views.py", line 12, in <module>
    from .forms import Form
  File "/Library/Python/2.7/site-packages/baseframe/forms/__init__.py", line 12, in <module>
    from .validators import *
  File "/Library/Python/2.7/site-packages/baseframe/forms/validators.py", line 6, in <module>
    import dns.resolver
  File "/Library/Python/2.7/site-packages/dns/resolver.py", line 35, in <module>
    import dns.message
  File "/Library/Python/2.7/site-packages/dns/message.py", line 191
    print('id %d' % self.id, file=s)
                                 ^
SyntaxError: invalid syntax
````

**Comment by jitendravyas** [comment]
Any update on this?

**Comment by renatomassaro** [comment]
In my case this was a conflict with `dnspython3`. Try uninstalling it, or reinstalling `dnspython` using `pip2`.

**Comment by jace** [comment]
How odd. Why does `pip` under Py2 install a Py3 version of `dnspython`?

**Comment by renatomassaro** [comment]
Yep, not sure what is going on but I had many problem with `dnspython` and `pip`, specifically. In my case I decided to automatically wget it from [their page](http://www.dnspython.org/) instead of relying on PyPi.

**Comment by tvvocold** [comment]
@renatomassaro 
Hi , I follow your way but still got same error. logs [here](http://pastebin.com/umwgzcVF)
 I had run $ pip unisntall dnspython && wget http://www.dnspython.org/kits/1.12.0/dnspython-1.12.0.tar.gz && tar -xvf dnspython-1.12.0.tar.gz && cd dnspython-1.12.0 && sudo python setup.py install . What's wrong and how to fix it? 
Thx:)

**Comment by renatomassaro** [comment]
@tvvocold This should do it, but if you are getting same OP error than you probably still have some `dnspython[3]` package lying around. Try something like `pip3 uninstall dnspython dnspython3 && pip2 uninstall dnspython dnspython3` to cover all packages.

**Comment by tvvocold** [comment]
Thx @renatomassaro ,
Looks like i am move forward to another error :)
```
tvvocold@hasjob:~/workspace (master) $ python manage.py db create
Traceback (most recent call last):
  File "manage.py", line 5, in <module>
    from hasjob.models import db
  File "/home/ubuntu/workspace/hasjob/__init__.py", line 32, in <module>
    from . import models, views  # NOQA
  File "/home/ubuntu/workspace/hasjob/models/__init__.py", line 68, in <module>
    from .jobpostreport import *
  File "/home/ubuntu/workspace/hasjob/models/jobpostreport.py", line 6, in <module>
    from .jobpost import JobPost
  File "/home/ubuntu/workspace/hasjob/models/jobpost.py", line 10, in <module>
    from sqlalchemy.dialects.postgresql import TSVECTOR
ImportError: cannot import name TSVECTOR
```
Why this and how to fix?

**Comment by jace** [comment]
What version of SQLAlchemy is this?

**Comment by tvvocold** [comment]
@jace 
> sqlalchemy.__version__ 
'0.8.4'

**Comment by jace** [comment]
Try the current release, 1.0.5.

**Comment by tvvocold** [comment]
Thx @jace ,
Another error.(I think there would be more, could you update the  [requirements.txt](https://github.com/hasgeek/hasjob/blob/master/requirements.txt) , so we can save some time? )
```
tvvocold@hasjob:~/workspace (master) $ python manage.py db create
Did not find settings file development.py for additional settings, skipping it
/usr/local/lib/python2.7/dist-packages/flask_cache/__init__.py:152: UserWarning: Flask-Cache: CACHE_TYPE is set to null, caching is effectively disabled.
  warnings.warn("Flask-Cache: CACHE_TYPE is set to null, "
Traceback (most recent call last):
  File "manage.py", line 13, in <module>
    manager.run()
  File "/usr/local/lib/python2.7/dist-packages/flask_script/__init__.py", line 351, in run
    result = self.handle(sys.argv[0], command, sys.argv[2:])
  File "/usr/local/lib/python2.7/dist-packages/flask_script/__init__.py", line 300, in handle
    command.run()
  File "/usr/local/lib/python2.7/dist-packages/flask_script/__init__.py", line 351, in run
    result = self.handle(sys.argv[0], command, sys.argv[2:])
  File "/usr/local/lib/python2.7/dist-packages/flask_script/__init__.py", line 324, in handle
    return command.handle(app, *positional_args, **command_namespace.__dict__)
  File "/usr/local/lib/python2.7/dist-packages/flask_script/commands.py", line 143, in handle
    return self.run(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/coaster/manage.py", line 70, in create
    manager.init_for(env)
  File "/home/ubuntu/workspace/hasjob/__init__.py", line 64, in init_for
    lastuser.init_app(app)
  File "/usr/local/lib/python2.7/dist-packages/flask_lastuser/__init__.py", line 301, in init_app
    self.lastuser_server = app.config['LASTUSER_SERVER']
KeyError: 'LASTUSER_SERVER'
```

**Comment by jace** [comment]
This is a runtime error. You need an `instance/development.py` with all the settings in `settings-sample.py`. Get your client id and secret from `auth.hasgeek.com`.

**Comment by tvvocold** [comment]
Can i don't use client id/secret to make it run? 
In another words, is this an opensouce project rely on auth.hasgeek.com?

**Comment by jace** [comment]
You van host your own auth server too if you like, but you'll need to make an id and password in it to continue.

**Comment by jace** [comment]
Hasjob has been updated to run inside Docker with all dependencies handled for you. Please refer to README.md for instructions.

**Comment by jitendravyas** [comment]
I have docker and composer install. Do I need to do git clone this repo inside docker?

**Comment by karthikb351** [comment]
@jitendravyas You git clone the repo, cd into it and run `docker-compose build`

**Comment by jitendravyas** [comment]
Ok I installed locally. pip-install went fine. copied all content from smaple file to settingf file and ran db command. Got below error

`````
~/projects/hasjob  master ✗                                             1d ⚑  ⍉
▶ sudo python manage.py db create
Traceback (most recent call last):
  File "manage.py", line 5, in <module>
    from hasjob.models import db
  File "/Users/jitendra.vyas/projects/hasjob/hasjob/__init__.py", line 12, in <module>
    from baseframe import baseframe, assets, Version
  File "/Library/Python/2.7/site-packages/baseframe/__init__.py", line 216, in <module>
    from .views import *    # NOQA
  File "/Library/Python/2.7/site-packages/baseframe/views.py", line 12, in <module>
    from .forms import Form
  File "/Library/Python/2.7/site-packages/baseframe/forms/__init__.py", line 12, in <module>
    from .validators import *
  File "/Library/Python/2.7/site-packages/baseframe/forms/validators.py", line 6, in <module>
    import dns.resolver
  File "/Library/Python/2.7/site-packages/dns/resolver.py", line 35, in <module>
    import dns.message
  File "/Library/Python/2.7/site-packages/dns/message.py", line 191
    print('id %d' % self.id, file=s)
                                 ^
SyntaxError: invalid syntax
````````````

**Comment by karthikb351** [comment]
Your issue is a duplicate of #207. As suggested, docker is the simplest way to set this up.
