### ISSUE TITLE
Update requirements.txt?

### ISSUE THREAD

**Issue by tvvocold** [hasgeek/hasjob#197]
Coz i got this error after $ pip install -r requirements.txt:
> $ python manage.py db create
Traceback (most recent call last):
  File "manage.py", line 3, in <module>
    from coaster.manage import init_manager
ImportError: No module named coaster.manage

BTW, i try pip/easy install  requirements.txt in openshift and ec2, both didn't work

$ python -V
```
Python 2.7.5 (default, Feb 11 2014, 07:46:25)
[GCC 4.8.2 20140120 (Red Hat 4.8.2-13)] on linux2
```

**Comment by jace** [comment]
You need to install Flask-Script==0.5.3. This version is in the requirements, but for some reason it doesn't always pick this specific version.

We're stuck with an outdated Flask-Script because Flask-Alembic is abandonware. There's a Flask-Migrate to replace it, but it's slightly different and we haven't gotten around to figuring out exactly what is different.

**Comment by tvvocold** [comment]
OK, i got the requirements,but still got errors:
```
tvvocold@hasjob:~/workspace (master) $ python manage.py db create                                                                                                
Traceback (most recent call last):
  File "manage.py", line 5, in <module>
    from hasjob.models import db
  File "/home/ubuntu/workspace/hasjob/__init__.py", line 12, in <module>
    from baseframe import baseframe, assets, Version
  File "/usr/local/lib/python2.7/dist-packages/baseframe/__init__.py", line 216, in <module>
    from .views import *    # NOQA
  File "/usr/local/lib/python2.7/dist-packages/baseframe/views.py", line 12, in <module>
    from .forms import Form
  File "/usr/local/lib/python2.7/dist-packages/baseframe/forms/__init__.py", line 12, in <module>
    from .validators import *
  File "/usr/local/lib/python2.7/dist-packages/baseframe/forms/validators.py", line 6, in <module>
    import dns.resolver
  File "/usr/local/lib/python2.7/dist-packages/dns/resolver.py", line 35, in <module>
    import dns.message
  File "/usr/local/lib/python2.7/dist-packages/dns/message.py", line 191
    print('id %d' % self.id, file=s)
                                 ^
SyntaxError: invalid syntax
```
How can i fix that?

**Comment by tvvocold** [comment]
https://github.com/hasgeek/hasjob/issues/193

**Comment by jace** [comment]
Yup, this is a dnspython issue. Closing this ticket to continue discussion there.
