### ISSUE TITLE
Not able to create DB in MacOS X

### ISSUE THREAD

**Issue by abhishekdgeek** [hasgeek/hasjob#207]
I have gone through and checked that I have right Flask-Script and sqlalchemy version. Also I have both dnspython dnspython3. But I still get this error on running "python manage.py db create"

Traceback (most recent call last):
  File "manage.py", line 5, in <module>
    from hasjob.models import db
  File "/Applications/MAMP/htdocs/office/hasjob/hasjob/__init__.py", line 12, in <module>
    from baseframe import baseframe, assets, Version
  File "/Library/Python/2.7/site-packages/baseframe/__init__.py", line 216, in <module>
    from .views import *    # NOQA
  File "/Library/Python/2.7/site-packages/baseframe/views.py", line 12, in <module>
    from .forms import Form
  File "/Library/Python/2.7/site-packages/baseframe/forms/__init__.py", line 12, in <module>
    from .validators import *
  File "/Library/Python/2.7/site-packages/baseframe/forms/validators.py", line 6, in <module>
    import dns.resolver
  File "/Library/Python/2.7/site-packages/dns/resolver.py", line 35, in <module>
    import dns.message
  File "/Library/Python/2.7/site-packages/dns/message.py", line 191
    print('id %d' % self.id, file=s)
                                 ^
SyntaxError: invalid syntax

Please help! :)

**Comment by jace** [comment]
Please uninstall dnspython3. This is a dependency from pyIsEmail and should be reported there as it is not required and causes problems.

**Comment by abhishekdgeek** [comment]
I did that too but then I got this:

python manage.py db create  
Traceback (most recent call last):
  File "manage.py", line 5, in <module>
    from hasjob.models import db
  File "/Applications/MAMP/htdocs/office/hasjob/hasjob/__init__.py", line 12, in <module>
    from baseframe import baseframe, assets, Version
  File "/Library/Python/2.7/site-packages/baseframe/__init__.py", line 216, in <module>
    from .views import *    # NOQA
  File "/Library/Python/2.7/site-packages/baseframe/views.py", line 12, in <module>
    from .forms import Form
  File "/Library/Python/2.7/site-packages/baseframe/forms/__init__.py", line 12, in <module>
    from .validators import *
  File "/Library/Python/2.7/site-packages/baseframe/forms/validators.py", line 6, in <module>
    import dns.resolver
ImportError: No module named dns.resolver

**Comment by jace** [comment]
Looks like you lost dnspython too then. Install only that.

**Comment by karthikb351** [comment]
Accounted for this in the docker branch [here](https://github.com/hasgeek/hasjob/blob/docker/Dockerfile#L22-L23)

```sh
pip2.7 uninstall dnspython3 -y
git clone https://github.com/rthalley/dnspython && cd dnspython && python setup.py install && cd .. && rm -rf dnspython
```

**Comment by abhishekdgeek** [comment]
@jace I have dnspython.
⇒  pip install dnspython        
Requirement already satisfied (use --upgrade to upgrade): dnspython in /Library/Python/2.7/site-packages

@karthikb351 
⇒  pip2.7 uninstall dnspython3 -y
Cannot uninstall requirement dnspython3, not installed

**Comment by abhishekdgeek** [comment]
Okay I uninstalled dnspython and run the command in sudo and it worked I guess.

git clone https://github.com/rthalley/dnspython && cd dnspython && sudo python setup.py install && cd .. && rm -rf dnspython

It somewhat inserted many things in DB and then this error came:

Traceback (most recent call last):
  File "manage.py", line 13, in <module>
    manager.run()
  File "/Library/Python/2.7/site-packages/flask_script/__init__.py", line 351, in run
    result = self.handle(sys.argv[0], command, sys.argv[2:])
  File "/Library/Python/2.7/site-packages/flask_script/__init__.py", line 300, in handle
    command.run()
  File "/Library/Python/2.7/site-packages/flask_script/__init__.py", line 351, in run
    result = self.handle(sys.argv[0], command, sys.argv[2:])
  File "/Library/Python/2.7/site-packages/flask_script/__init__.py", line 324, in handle
    return command.handle(app, *positional_args, **command_namespace.__dict__)
  File "/Library/Python/2.7/site-packages/flask_script/commands.py", line 143, in handle
    return self.run(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/coaster/manage.py", line 72, in create
    manager.db.create_all()
  File "/Library/Python/2.7/site-packages/flask_sqlalchemy/__init__.py", line 895, in create_all
    self._execute_for_all_tables(app, bind, 'create_all')
  File "/Library/Python/2.7/site-packages/flask_sqlalchemy/__init__.py", line 887, in _execute_for_all_tables
    op(bind=self.get_engine(app, bind), **extra)
  File "/Library/Python/2.7/site-packages/sqlalchemy/sql/schema.py", line 3687, in create_all
    tables=tables)
  File "/Library/Python/2.7/site-packages/sqlalchemy/engine/base.py", line 1856, in _run_visitor
    conn._run_visitor(visitorcallable, element, **kwargs)
  File "/Library/Python/2.7/site-packages/sqlalchemy/engine/base.py", line 1481, in _run_visitor
    **kwargs).traverse_single(element)
  File "/Library/Python/2.7/site-packages/sqlalchemy/sql/visitors.py", line 121, in traverse_single
    return meth(obj, **kw)
  File "/Library/Python/2.7/site-packages/sqlalchemy/sql/ddl.py", line 730, in visit_metadata
    _is_metadata_operation=True)
  File "/Library/Python/2.7/site-packages/sqlalchemy/sql/visitors.py", line 121, in traverse_single
    return meth(obj, **kw)
  File "/Library/Python/2.7/site-packages/sqlalchemy/sql/ddl.py", line 764, in visit_table
    include_foreign_key_constraints=include_foreign_key_constraints
  File "/Library/Python/2.7/site-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/Library/Python/2.7/site-packages/sqlalchemy/sql/ddl.py", line 68, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "/Library/Python/2.7/site-packages/sqlalchemy/engine/base.py", line 962, in _execute_ddl
    compiled = ddl.compile(dialect=dialect)
  File "<string>", line 1, in <lambda>
  File "/Library/Python/2.7/site-packages/sqlalchemy/sql/elements.py", line 494, in compile
    return self._compiler(dialect, bind=bind, **kw)
  File "/Library/Python/2.7/site-packages/sqlalchemy/sql/ddl.py", line 26, in _compiler
    return dialect.ddl_compiler(dialect, self, **kw)
  File "/Library/Python/2.7/site-packages/sqlalchemy/sql/compiler.py", line 190, in __init__
    self.string = self.process(self.statement, **compile_kwargs)
  File "/Library/Python/2.7/site-packages/sqlalchemy/sql/compiler.py", line 213, in process
    return obj._compiler_dispatch(self, **kwargs)
  File "/Library/Python/2.7/site-packages/sqlalchemy/sql/visitors.py", line 81, in _compiler_dispatch
    return meth(self, **kw)
  File "/Library/Python/2.7/site-packages/sqlalchemy/sql/compiler.py", line 2164, in visit_create_table
    (table.description, column.name, ce.args[0])
  File "/Library/Python/2.7/site-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/Library/Python/2.7/site-packages/sqlalchemy/sql/compiler.py", line 2153, in visit_create_table
    and not first_pk)
  File "/Library/Python/2.7/site-packages/sqlalchemy/sql/compiler.py", line 213, in process
    return obj._compiler_dispatch(self, **kwargs)
  File "/Library/Python/2.7/site-packages/sqlalchemy/sql/visitors.py", line 81, in _compiler_dispatch
    return meth(self, **kw)
  File "/Library/Python/2.7/site-packages/sqlalchemy/sql/compiler.py", line 2184, in visit_create_column
    first_pk=first_pk
  File "/Library/Python/2.7/site-packages/sqlalchemy/dialects/sqlite/base.py", line 847, in get_column_specification
    column.type, type_expression=column)
  File "/Library/Python/2.7/site-packages/sqlalchemy/sql/compiler.py", line 261, in process
    return type_._compiler_dispatch(self, **kw)
  File "/Library/Python/2.7/site-packages/sqlalchemy/sql/visitors.py", line 79, in _compiler_dispatch
    raise exc.UnsupportedCompilationError(visitor, cls)
sqlalchemy.exc.CompileError: (in table 'domain', column 'search_vector'): Compiler <sqlalchemy.dialects.sqlite.base.SQLiteTypeCompiler object at 0x10db5fc10> can't render element of type <class 'sqlalchemy.dialects.postgresql.base.TSVECTOR'>

Am I good to go?

**Comment by karthikb351** [comment]
@abhishekdgeek Docker is the easiest way to set up hasjob right now.
Could you switch the docker branch and follow the Docker instructions in the Readme?

**Comment by jace** [comment]
The `docker` branch is now merged into `master`. Please use that if you are unable to get dependencies installed normally.
